### PR TITLE
Revive

### PR DESCRIPTION
**Pull request by eric-burel**
This PR is for tracking the revival of this project, as having a CLI for Vulcan makes it really awesome.

Current version does not work, at least on my computer, when it comes to generate package. The goal is to fix this and update this package to the last version of Vulcan.

Please do not merge yet.

- [X]  Manually test the generators to check what is ok, what is not
- [X] `vulcan create` clone the Vulcan repo, maybe it should clone the starter instead
- [X] Right now, a redux store is used to remember the packages created automatically, in order to list them later. However this will be inconsistent when some packages are preexisting or created manually. Get rid of the use of a Redux store to handle listing of packages, modules and routes. Those information should be retrieved directly from the folder structure or the related files instead.
See the new `lib/lister.js` file
- [X] Use the lister in the assertion lib
- [X] Use the lister in the `validations` lib
- [X] Update to last version of Vulcan
- [X] Get rid of the current finalization behaviour. Right now, if you pass arguments, you will still be prompted questions. But during the call to `_finalize`, the prompted questions are ignored anyway. *Done but a bit ugly and messy (check is very manual).*
- [X]  Fix the "list" commands. *Now only packages can be listed, with a brief summary. Use direclty the `vulcan:debug` package for more info about the app.*
- [ ] Scaffold test (see `vulcan-forms` package for an example) *Low priority*
- [ ] Remove unused features to make the CLI maintenance easier: stories generation etc. *Mostly done*
- [X] Rename "model" to "module" to avoid confusions
- [X] Setup a micro-test, in the form of a script that generate an app.

### CODE REVIEW

**Comment by eric-burel** [comment]
Hi @mechanical-turk and @albancrommer , 

I have struggle to understand what happened the last time this framework was updated. There seemed to have been a breaking change on the master branch that was reverted in the devel. Do you remember what was the issue?
Also, why did you need a `vulcan init` command? I don't get its purpose, it seems to persist some information about the current folder but I fail to see why they are necessary.

Also, it is the first time I work on a public npm package, what will be the process to publish an update when I am done with updating the project?

Thanks in advance for your help and also for your earlier work on this CLI, I hope to get things working again very soon.

**Comment by mechanical-turk** [comment]
Hi @eric-burel,

I believe it's been longer than a year since alban and I last worked on this project. I've always personally found it really difficult to take over an abandoned project and revive it. Even though Vulcan is thriving, the cli is pretty much obsolete. I think you'll be better off starting over, as I'm sure many of the assumptions baked in to the cli have changed as Vulcan matured during my absence. With that, I have to add that I won't be able to offer much help. 

I'll be very happy to hand over the npm namespace though. Feel free to ping me here. 

Best of luck.

**Comment by albancrommer** [comment]
Hey @eric-burel @mechanical-turk 

I understand Kerem. You might find yourself more or less swamped into an outdated approach.

In my opinion, the best option would be to 
- Define. Should cli be clever or stupid. Stupid is fast and 90% sufficent. Which Actions should be avail. and so on
- Strip. Keep most of the boilerplate i.e. yeoman 
- Code. Implement required actions to work with current vulcan-state 

Maybe a visioconf would help. Could help with setting npm up together and talking about that?

**Comment by eric-burel** [comment]
Thanks @mechanical-turk and @albancrommer for your answers.

Actually you may underestimate your work, you did a pretty good job and I had not much trouble to grasp the structure of the code. I have updated the files to match Vulcan current structure and it is pretty much the same as one year ago, Vulcan's core API is quite stable, same with Yeoman, your code could have been written weeks ago :). 
It is mostly working and up to date after the few last commits, I am only a few hours away to get a publishable new version.

I'll go for a very simple CLI, with indeed a focus on the Yeoman code generation part, I think I will even remove "list" and "remove" methods. 

I now understand a bit better why you did set a redux store to remember the packages created by the user.  Last year have been a "Redux experimentation period" for a lot of people by the way, me included, it is interesting to see it in a CLI. 
I am however replacing this with functions that will directly look in the folders to detect packages, components, routes. The app structure and files is itself a "store", that contains information about the packages, the modules etc. so using redux is equivalent to creating multiple sources of truth, which explains my initial struggles.

I've just created a npm account "eric-burel" (eb@lebrun-burel.com). Right now I am on holidays (stuck in a train that is very late to be precise...) but I'd be glad to talk about it directly depending on how this project evolve in the weeks to come. Vulcan has now more traction so other people might be interested in upgrading the CLI after I get it back on its feet.

**Comment by mechanical-turk** [comment]
@eric-burel i really like your enthusiasm and initiative. just added you as an admin to the npm package, so you should be able to start publishing new packages. excited to see where you can take this project. good luck

**Comment by SachaG** [comment]
Awesome work everybody and thanks @eric-burel for reviving this project!

**Comment by eric-burel** [comment]
Thanks for your support :) This should be working now @mechanical-turk, thanks for adding me on npmjs. This branch is now mergeable, I did a few tests and all the public commands should work as expected.
Can you please give me also write access to this repo too so that I can handle merges?

I'll do a bit more testing and then publish it on npm :tada:. 

In the (far) future I'd like to create an UI to generate packages, modules etc., in the form of a Vulcan package, instead of an independant CLI (though this interface could itself rely on the CLI for some features). It may be more efficient because a Vulcan package would be directly able to list the existing packages, collections and routes like `vulcan:debug` does and would allow more complex workflows.

So I'll handle maintaince on this package (at least in the months to come) but keep it to the minimum: updating to new Vulcan versions, fixing bugs in existing features, few enhancements. I think that's the most reasonable way to maintain a CLI anyway. 

Thanks again for your answers and your initial work on this tool!

**Comment by mechanical-turk** [comment]
Hi @eric-burel! I could give you access to the npm package but I cant give you write access here as I don't have admin access here. @SachaG can though!

**Pull request merged**
